import Head from 'next/head'
import Link from 'next/link'
import { React } from "react";

export default function Forgetpassword() {


  
  return (
    <div>
      <Head>
        <title>Project Management</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/Project.svg" />
      </Head>

      <main className="font-Roboto bg-white flex flex-col justify-center items-center  h-screen  ">

        {/* <div className="flex flex-col bg-[#DCE4FF] justify-center px-[3rem] pb-[4rem]  drop-shadow-xl ">

            <p className="text-black text-[2rem] font-semibold mt-[2rem]  ">Forgot Password</p>

            <form className="flex flex-col text-black ">
                <input
                  className="text-black text-[1.2rem] bg-[#DCE4FF] border-2 border-[#EAEFF2] w-[45rem]  pt-[1.4rem] pb-[2.2rem] pl-[1.9rem] mt-[2.2rem] "
                  id="Email"
                  type="email"
                  placeholder="Email"
                  required
                />  
              <Link href="">
                <button className="text-white text-[2rem] font-medium bg-darkblue w-[45rem]  py-[1.4rem] mt-[2.2rem]">
                    Forgot Password
                </button>
              </Link>
            </form>

        </div> */}



        {/* new password */}

        <div className="flex flex-col bg-[#DCE4FF] justify-center px-[3rem] pb-[10rem]  drop-shadow-xl ">

            <p className="text-black text-[2rem] font-semibold mt-[8rem]  ">Reset Password</p>

            <form className="flex flex-col text-black ">
                <input
                  className="text-black text-[1.2rem] bg-[#DCE4FF] border-2 border-[#EAEFF2] w-[45rem]  pt-[1.4rem] pb-[2.2rem] pl-[1.9rem] mt-[2.2rem] "
                  id="Password"
                  type="email"
                  placeholder="New Password"
                  required
                />
                <input
                  className="text-black text-[1.2rem] bg-[#DCE4FF] border-2 border-[#EAEFF2] w-[45rem]  pt-[1.4rem] pb-[2.2rem] pl-[1.9rem] mt-[2.2rem] "
                  id="Password"
                  type="email"
                  placeholder="Confirm Password"
                  required
                />
              <Link href="">
                <button className="text-white text-[2rem] font-medium bg-darkblue w-[45rem]  py-[1.4rem] mt-[2.2rem]">
                    Forgot Password
                </button>
              </Link>
            </form>

        </div>
        
      </main>

    </div>
  )
}
