import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import Icon from "../../public/assets/Icon.svg"
import Mark from "../../public/assets/Mark.svg"
import { React, useState } from "react";

export default function Appointment() {


  
  return (
    <div>
      <Head>
        <title>Project Management</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/Project.svg" />
      </Head>

      <main className="font-Roboto bg-[#DCE4FF] flex flex-col justify-center items-center  h-screen  ">

        <div className="flex bg-white justify-center w-[60rem] h-[75vh]">
        
            <div className="flex flex-col bg-deepblue w-1/4 pt-[3rem] text-center ">
                    <div className="font-semibold text-[2rem] text-white mt-[1rem] ">Appointment</div>
                <Link href="">
                    <div className="font-semibold text-[2rem] text-white mt-[2rem] hover:bg-white hover:text-black">Create</div>
                </Link>
                <Link href="">
                    <div className="font-semibold text-[2rem] text-white mt-[2rem] hover:bg-white hover:text-black">View</div>
                </Link>
                
            </div>
            <div  className="bg-white ml-[2rem] w-3/4 pt-[6rem] pb-[8rem] ">
                <p className="text-[#03122F] text-[2rem] font-semibold text-center ">MEETING DETAIL</p>
                <form>
                <div className="flex mt-[4rem]">
                <label className=" text-[#03122F] self-center font-semibold text-[2rem] w-[12rem] ">
                Student ID:
                </label>
                <input
                    className="text-black text-[1.6rem] bg-white border border-[#03122F] w-[30rem] pt-[0.6rem] pb-[0.5rem] pl-[1.5rem]  "
                    type="text"
                    required
                />
                </div>
                <div className="flex mt-[4rem]">
                <label className=" text-[#03122F] self-center font-semibold text-[2rem] w-[12rem]  ">
                Date:
                </label>
                <input
                    className="text-black text-[1.6rem] bg-white border border-[#03122F] w-[30rem] pt-[0.6rem] pb-[0.5rem] pl-[1.5rem]  "
                    type="text"
                    required
                />
                </div>
                <div className="flex mt-[4rem]">
                <label className=" text-[#03122F] self-center font-semibold text-[2rem] w-[12rem]  ">
                Start time:
                </label>
                <input
                    className="text-black text-[1.6rem] bg-white border border-[#03122F] w-[30rem] pt-[0.6rem] pb-[0.5rem] pl-[1.5rem]  "
                    type="text"
                    required
                />
                </div>
                <div className="flex mt-[4rem]">
                <label className=" text-[#03122F] self-center font-semibold text-[2rem]  w-[12rem] ">
                End time:
                </label>
                <input
                    className="text-black text-[1.6rem] bg-white border border-[#03122F] w-[30rem] pt-[0.6rem] pb-[0.5rem] pl-[1.5rem]  "
                    type="text"
                    required
                />
                </div>
                <Link href="">
                    <button className="text-white text-[2.4rem] font-medium bg-[#03122F] w-[27rem] py-[0.9rem] ml-[7rem] mt-[6rem]">
                        Submit
                    </button>
                </Link>
                </form>
            </div>

        </div>

        {/* View */}

        {/* <div className="flex bg-white justify-center w-[60rem] h-[75vh]">
        
            <div className="flex flex-col bg-deepblue w-1/4 pt-[3rem] text-center ">
                    <div className="font-semibold text-[2rem] text-white mt-[1rem] ">Appointment</div>
                <Link href="">
                    <div className="font-semibold text-[2rem] text-white mt-[2rem] hover:bg-white hover:text-black">Create</div>
                </Link>
                <Link href="">
                    <div className="font-semibold text-[2rem] text-white mt-[2rem] hover:bg-white hover:text-black">View</div>
                </Link>
                
            </div>
            <div  className="bg-white ml-[2rem] w-3/4 pt-[6rem] pb-[8rem] ">
                <p className="text-[#03122F] text-[2rem] font-semibold text-center ">MEETING DETAIL</p>
                <form>
                <div className="flex mt-[4rem]">
                <label className=" text-[#03122F] self-center font-semibold text-[2rem] w-[12rem]  ">
                Date:
                </label>
                <input
                    className="text-black text-[1.6rem] bg-white border border-[#03122F] w-[30rem] pt-[0.6rem] pb-[0.5rem] pl-[1.5rem]  "
                    type="text"
                    required
                />
                </div>
                <div className="flex mt-[4rem]">
                <label className=" text-[#03122F] self-center font-semibold text-[2rem] w-[12rem]  ">
                Start time:
                </label>
                <input
                    className="text-black text-[1.6rem] bg-white border border-[#03122F] w-[30rem] pt-[0.6rem] pb-[0.5rem] pl-[1.5rem]  "
                    type="text"
                    required
                />
                </div>
                <div className="flex mt-[4rem]">
                <label className=" text-[#03122F] self-center font-semibold text-[2rem]  w-[12rem] ">
                End time:
                </label>
                <input
                    className="text-black text-[1.6rem] bg-white border border-[#03122F] w-[30rem] pt-[0.6rem] pb-[0.5rem] pl-[1.5rem]  "
                    type="text"
                    required
                />
                </div>
                </form>
            </div>

        </div> */}
        
      </main>

    </div>
  )
}
