import Head from "next/head";
import Link from "next/link";
import { React, useState } from "react";

export default function Comment() {
  const [track, setTrack] = useState(0);

  return (
    <div>
      <Head>
        <title>Project Management</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/Project.svg" />
      </Head>

      <main className="font-Roboto bg-[#DCE4FF] flex flex-col justify-center items-center  h-screen  ">
        {track === 0 ? (
          <div className="flex bg-white justify-center w-[55rem] h-[75vh]">
            <div className="flex flex-col bg-deepblue w-1/4 pt-[3rem] text-center ">
              <Link href="/dashboard/dashboard">
                <div className="font-semibold text-[2rem] text-white mt-[1rem] hover:bg-white hover:text-black">
                  Comments
                </div>
              </Link>
              <Link href="" onClick={() => setTrack((track) => !track)}>
                <div className="font-semibold text-[2rem] text-white mt-[2rem] hover:bg-white hover:text-black">
                  Intern
                </div>
              </Link>
              <div className="font-semibold text-[2rem] mt-[2rem] bg-white text-black">
                Staff
              </div>
            </div>
            <div className="bg-white ml-[2rem] w-3/4 pt-[6rem] pb-[8rem] ">
              <p className="text-[#03122F] text-[2rem] font-semibold pl-[2.5rem]">
                General comments on project
              </p>
              <form>
                <div className="flex justify-center mt-[0.8rem] ">
                  <input
                    className=" text-black text-[1.6rem] bg-white border border-[#03122F] w-[34rem] h-[23rem] pt-[0.6rem] pb-[0.5rem] pl-[1.5rem]  "
                    type="text"
                    required
                  />
                </div>
                <Link href="" className="flex justify-center">
                  <button className="text-white text-[2.4rem] font-medium bg-[#03122F] w-[27rem] py-[0.9rem] mt-[3rem] ">
                    Send notification
                  </button>
                </Link>
              </form>
            </div>
          </div>
        ) : (
          <div className="flex bg-white justify-center w-[55rem] h-[75vh]">
            <div className="flex flex-col bg-deepblue w-1/4 pt-[3rem] text-center ">
              <Link href="/dashboard/dashboard">
                <div className="font-semibold text-[2rem] text-white mt-[1rem] hover:bg-white hover:text-black ">
                  Comments
                </div>
              </Link>
              <div className="font-semibold text-[2rem]  mt-[2rem] bg-white text-black">
                Intern
              </div>
              <Link href="" onClick={() => setTrack(0)}>
                <div className="font-semibold text-[2rem] text-white mt-[2rem] hover:bg-white hover:text-black">
                  Staff
                </div>
              </Link>
            </div>
            <div className="bg-white ml-[2rem] w-3/4 pt-[6rem] pb-[8rem] ">
              <p className="text-[#03122F] text-[2rem] font-semibold pl-[2.5rem] ">
                Comments from supervisor
              </p>
              <form>
                <div className="flex justify-center mt-[0.8rem] ">
                  <input
                    className=" text-black text-[1.6rem] bg-white border border-[#03122F] w-[34rem] h-[23rem] pt-[0.6rem] pb-[0.5rem] pl-[1.5rem]  "
                    type="text"
                    required
                  />
                </div>
                <div className="flex justify-between mx-[3rem] ">
                  <Link href="">
                    <button className="text-white text-[2rem] font-medium bg-[#03122F] w-[14rem] py-[0.9rem] mt-[3rem] ">
                      Ask question?
                    </button>
                  </Link>
                  <Link href="">
                    <button className="text-white text-[2rem] font-medium bg-[#03122F] w-[14rem] py-[0.9rem] mt-[3rem] ">
                      Understood?
                    </button>
                  </Link>
                </div>
              </form>
            </div>
          </div>
        )}
      </main>
    </div>
  );
}
