import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { React, useState } from "react";
import Dash from "../../public/assets/Dashboard.svg"
import Proj from "../../public/assets/Project.svg"

export default function Dashboard() {


  
  return (
    <div>
      <Head>
        <title>Project Management</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/Project.svg" />
      </Head>

      <main className="font-Roboto bg-white w-full flex h-screen  ">
       
        <div className="w-1/5 bg-deepblue h-screen ">

            <div className="flex flex-col">
                <div className="flex space-x-4 mt-[4.2rem]">
                    <Image src={Dash} alt="Dashboard"/>
                    <div className="font-semibold text-[2rem] text-white  ">Dashboard</div>
                </div>
                <div className="flex  cursor-pointer space-x-4 mt-[3rem] hover:bg-white hover:text-black">
                    <Image src={Dash} alt="Dashboard"/>
                    <div className="font-semibold text-[2rem] text-white  ">Project</div>
                </div>
                <div className="flex cursor-pointer space-x-4 mt-[3rem]">
                    <Image src={Dash} alt="Dashboard"/>
                    <div className="font-semibold text-[2rem] text-white  ">Comment</div>
                </div>
                <div className="flex cursor-pointer space-x-4 mt-[3rem]">
                    <Image src={Dash} alt="Dashboard"/>
                    <div className="font-semibold text-[2rem] text-white  ">Appointment</div>
                </div>
                <div className="flex cursor-pointer space-x-4 mt-[3rem]">
                    <Image src={Dash} alt="Dashboard"/>
                    <div className="font-semibold text-[2rem] text-white  ">Intern</div>
                </div>
                <div className="flex cursor-pointer space-x-4 mt-[3rem]">
                    <Image src={Dash} alt="Dashboard"/>
                    <div className="font-semibold text-[2rem] text-white  ">Staff</div>
                </div>
                
            </div>
        </div>
        <div className="w-4/5 bg-white h-screen ">
            {/* <div className="flex flex-row-reverse">I see you</div> */}
            <div class="flex flex-col justify-center items-center h-screen">
                <h1 className="text-[4rem] tetx-deepblue font-bold ">Project Management System</h1>
                <div className="grid grid-cols-2">
                    <div>1</div>
                    <div>2</div>
                    <div>3</div>
                    <div>4</div>
                </div>
            </div>
            
        </div>
      </main>

    </div>
  )
}
