import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { React } from "react";
import Dash from "../../public/assets/Dashboard.svg";
import Project from "../../public/assets/Project.svg";
import Comment from "../../public/assets/Comment.svg";
import Appointment from "../../public/assets/Appointment.svg";
import Search from "../../public/assets/Search.svg";
import Profile from "../../public/assets/Profile.svg";
import Edit from "../../public/assets/Edit.svg";
import Arrowdown from "../../public/assets/Arrowdown.svg";
import Rectangle from "../../public/assets/Rectangle.png";
import Notification from "../../public/assets/Notification.svg";
import Logout from "../../public/assets/Logout.svg";
import Logout_Two from "../../public/assets/Logout_Two.svg";


export default function Dashboard() {
  return (
    <div>
      <Head>
        <title>Project Management</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/Project.svg" />
      </Head>

      <main className="font-Roboto bg-white w-full flex h-screen  ">
        <div className="w-1/5 bg-deepblue h-screen ">
          <div className="flex flex-col  text-white ">
            <div className="flex space-x-4 mt-[4.2rem] px-[4rem] py-[1rem] ">
              <Image src={Dash} alt="Dashboard" />
              <div className="font-semibold text-[2rem]  ">Dashboard</div>
            </div>
            <Link href="/dashboard/createprojectpopup">
              <div className="flex  space-x-4 mt-[3rem] px-[4rem] py-[1rem] hover:bg-white hover:text-black">
                <Image src={Project} alt="Project" />
                <div className="font-semibold text-[2rem]  ">Project</div>
              </div>
            </Link>
            <Link href="/dashboard/comment">
              <div className="flex  space-x-4 mt-[3rem] px-[4rem] py-[1rem] hover:bg-white hover:text-black">
                <Image src={Comment} alt="Comment" />
                <div className="font-semibold text-[2rem] ">Comment</div>
              </div>
            </Link>
            <Link href="/dashboard/appointment">
              <div className="flex space-x-4 mt-[3rem] px-[4rem] py-[1rem] hover:bg-white hover:text-black">
                <Image src={Appointment} alt="Appointment" />
                <div className="font-semibold text-[2rem]  ">Appointment</div>
              </div>
            </Link>
          </div>
        </div>
        <div className="w-4/5 bg-white">
        <div className="flex justify-end mt-[1rem] mx-[3rem] ">
            <Link href="" >
                <div className="flex relative mx-[1.2rem]">
                    <Image src={Notification} alt="Notification" className=" mt-[0.7rem] " />
                    <span className="absolute top-[1.3rem] right-[0rem] bg-[#F02727] rounded-full w-[1rem] h-[1rem]"></span>
                </div>
            </Link>
            <Image
                src={Rectangle}
                alt="Rectangle"
                className="w-[5rem] h-[5rem] "
            />
            <div className="flex flex-col px-[0.8rem] mt-[1.5rem] ">
                <p className=" text-[#03122F] text-[1.2rem]  ">
                Adedeji Adelanwa
                </p>
                <p className=" text-[#808080] text-[1.2rem]">Intern</p>
            </div>
            <Image src={Arrowdown} alt="Arrow" />
            <Link href="/" className="self-center bg-[#F02727] px-[0.8rem] py-[0.3rem] mx-[1rem]">
                <h6 className=" text-[1.8rem] font-medium text-white ">Log out</h6>
            </Link>
        </div>
        <div className="flex flex-col items-center ">
            
        <h1 className="text-[4rem] text-deepblue font-bold mt-[7rem]">
            Project Management System
        </h1>
        <div className="grid grid-cols-2 gap-[6rem] place-content-evenly mt-[0rem] ">
            <Link href="/dashboard/createprojectpopup">
            <div className="flex flex-col bg-[#ECF2FF] w-[15rem] h-[15rem] justify-center items-center ">
                <Image src={Edit} alt="Edit" />
                <h2 className="text-[1.8rem] font-medium text-[#03122F] mt-[2.5rem] ">
                View Project
                </h2>
            </div>
            </Link>
            <Link href="">
            <div className="flex flex-col bg-[#ECF2FF] w-[15rem] h-[15rem] justify-center items-center ">
                <Image src={Search} alt="Search" />

                <h3 className="text-[1.8rem] font-medium text-[#03122F] mt-[2.5rem] ">
                Search
                </h3>
            </div>
            </Link>
            <Link href="/dashboard/editprofile">
            <div className="flex flex-col bg-[#ECF2FF] w-[15rem] h-[15rem] justify-center items-center ">
                <Image src={Profile} alt="Profile" />

                <h4 className="text-[1.8rem] font-medium text-[#03122F] mt-[2.5rem] ">
                Edit profile
                </h4>
            </div>
            </Link>
            <Link href="/">
            <div className="flex flex-col bg-[#ECF2FF] w-[15rem] h-[15rem] justify-center items-center ">
                <div className="flex relative">
                <Image src={Logout_Two} alt="Logout_Two" />
                <Image
                    src={Logout}
                    alt="Logout"
                    className="absolute top-[1rem] right-[-1rem] "
                />
                </div>

                <h5 className="text-[1.8rem] font-medium text-[#03122F] mt-[2.5rem] ">
                Log out
                </h5>
            </div>
            </Link>
        </div>
        </div>
        </div>
      </main>
    </div>
  );
}
