import Head from "next/head";
import { React, useEffect, useState, useRef } from "react";
import Link from "next/link";
import axios from "axios";
import { useRouter } from "next/router";

function Viewprojects({  }) {
  const router = useRouter();
  const { project_id } = router.query;

  useEffect(()=>{

  },[])

  const [project_title, setProject_title] = useState([]);
  const [description, setDescription] = useState([]);
  const [id, setId] = useState([]);
  const [project, setProject] = useState({});

  useEffect(() => {
    axios
      .get(`http://localhost:8082/api/project/${project_id}`)
      .then((res) => {
        setProject_title(res.data);
        setDescription(res.data);
        setProject(res.data);
       
        console.log("value of project", res.data);
      })
      .catch((err) => {
        console.log(err);
      });
  }, [project_id]);

  return (
    <div>
    
      <Head>
      
        <title>Project Management</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/Project.svg" />
      </Head>

      <main className="font-Roboto bg-[#DCE4FF] flex flex-col justify-center items-center  h-screen  ">
        <div className="flex flex-col bg-white justify-center text-black font-semibold text-[2.4rem] p-[5rem] w-[60rem] h-[40rem] rounded-[3rem] drop-shadow-xl ">
          <div className="flex flex-col justify-between px-[3rem]">
            <p className="">Project Title: </p>
            {project.project_title}
          </div>
          <div className="flex flex-col justify-between mt-[5rem] px-[3rem]">
            <p className=""> Description:</p>
            {project.description}
          </div>

          <Link
            href="/dashboard/createprojectpopup "
            className="self-end mt-[2rem] "
          >
            <button className="text-white text-[2rem] font-medium bg-[#292626] px-[1rem] py-[0.5rem] mx-[1rem] ">
              Cancel
            </button>
          </Link>
        </div>
      </main>
    </div>
  );
}

export default Viewprojects;
